### ISSUE TITLE
invalid character 'ÿ'

### ISSUE THREAD

**Issue by crazyyzarc** [fofapro/fapro#6]
When I run the service, it will be stopped. I use an English keyboard

![2021-09-30_14-52-17-298_bvrvi](https://user-images.githubusercontent.com/4954535/135458796-4876e98e-bd3a-4c7c-b323-123205f0d592.png)

**Comment by ntestoc3** [comment]
The configuration file generated under windows powershell cannot be run
./fapro run prompt:

panic: Fatal error config file: While parsing config: invalid character 'ÿ' looking for beginning of value

Because the output encoding of powershell stdout redirect is UTF-8 with BOM, Use Out-File command to save the configuration file.

./fapro.exe genConfig -n 172.16.0.0/16 | Out-File -Encoding ASCII fapro.json
